### ISSUE TITLE
Reworking 'priority' channels

### ISSUE THREAD

**Issue by miweber67** [lordmorgul/ham2mon#5] opened 2022-12-04 01:11 UTC
First, nice work on consolidating the contributions various folks have made and adding a bunch of your own. Nice to see.

I was looking at the implementation of 'priority' channels and it seems a few things need correcting. Before I jumped in to coding I thought I'd talk through some of them and see if anyone else was already working on these issues.

First, it appears that the 'priority channel' frequencies are always assigned to demodulators. If you have more priority channels than demodulators, you will never pick up any activity on any channel other than the first N priority channels. If you have 8 priority channels and 4 demodulators, you'll never hear activity on priority channels 5-8 because the code assigns demodulators to all of the priority channels from scanner.priority_channels regardless if they're active or not. This seems wasteful at best and will cause the scanner to miss signals it could otherwise receive at worst. If your machine is beefy enough I suppose you could assign a huge number of demodulators and be OK just writing everything to files, but I have a different use case in mind.

My use case is this: Sometimes I want to hear something, anything, but I want to hear certain things over other things if they're actually happening. That means I have one demodulator and I'm feeding it to my speakers. My local repeaters are the most interesting to me, and of course I prefer some over others. If all of the repeaters are idle, perhaps I want to hear what's on simplex frequencies, but only so long as the repeaters are idle... if a channel more important to me becomes active, I want a lesser channel to be dropped in favor of the channel with "more" priority.

That implies two things to me: 1, that the frequencies in a priority file have an internal ranking, be it implicit in their order in the file or made explicit through the addition of a priority field; and 2, that the handling of priority channels needs to be reworked to avoid the apparent bug I mentioned at the top of this post.

I'm happy to work this issue but didn't want to step on anyone's toes, nor miss some other use cases that might point to some other features to add at the same time.

Best,
Mike

**Comment by lordmorgul** [comment] 2023-02-18 19:51
Hi Mike, sorry for not seeing your issue posted sooner.  Yes that limitation of priority channels consuming the available demodulators is a challenge I had not looked at trying to resolve yet.  I'd be interested if you have ideas on the resolution for it.  I agree with how you are stating the use case, that was exactly what was intended by starting work toward priority channels, but the most direct method to get there was ensure that at least a demodulator was assigned to that channel.

My use case driving it was this:
1) configure a demodulator to a GMRS repeater input, set priority channel
2) add additional demodulators when machine CPU can handle more
3) always capture input transmissions to the repeater

**Comment by lordmorgul** [comment] 2023-02-18 20:17
I updated comment above, if email didn't notify this should.  No toes being stepped on if you work on it, happy to capture if you work it in your repo and get working let me know.

**Comment by lordmorgul** [comment] 2024-02-04 06:54
Closing as manually completed with additional re-writes.  Merging the branch with this change into Master now and then will migrate it into the john- repo where further development is focused.

**Closed by lordmorgul** 2024-02-04 06:54 UTC
